### ISSUE TITLE
The Toasts Room

### ISSUE THREAD

**Issue by notcarlton** [JiayiSoftware/JiayiLauncher#1]
general discussion for how to implement toasts. even if you're not a developer, you can throw in your two cents on how they should look and behave

**Comment by DeathlyBower959** [comment]
I would think you would want it to be in app, not as a separate window, and probably just in the top right of the app? Eased animation etc.

Atomic Ideas:
 - Accent border color
 - Animated rtl
 - Rounded
 - Title in top left of toast, text indented below
 - Title also in accent color
 - uhhhhhhh

**Comment by notcarlton** [comment]
noted

**Comment by notcarlton** [comment]
gonna have to start implementing this after release because I don't have enough time
