### ISSUE TITLE
Un-fuck drop down boxes

### ISSUE THREAD

**Issue by notcarlton** [JiayiSoftware/JiayiLauncher#2]
the code is a mess, so let's fix it

**Comment by Plextora** [comment]
elaborate

**Comment by notcarlton** [comment]
https://github.com/JiayiSoftware/JiayiLauncher/blob/master/JiayiLauncher/Shared/Components/JiayiDropDown.razor

**Comment by notcarlton** [comment]
the styles are scuffed too, a lot of weird hacks there https://github.com/JiayiSoftware/JiayiLauncher/blob/master/JiayiLauncher/Shared/Components/JiayiDropDown.razor.css

**Comment by Plextora** [comment]
gonna be honest can't really help with this, I've never worked with blazor shit and im terrible at css
