### ISSUE TITLE
Proposal: Consider using Appx Packages

### ISSUE THREAD

**Issue by CXCubeHD** [JiayiSoftware/JiayiLauncher#27]
This would have many advantages:
- Easy installation
- Easy to uninstall
- Follows the overall standard of a Windows application
- Allows to reset app data from settings (and cache, ...)
- File extension can be specified in package manifest
- Easy for other apps to find the program on your system

Edit:
- You can (or need to) sign the appx package, this would allow people verify that the package is legit
- *(Microsoft Store!?)*

**Comment by notcarlton** [comment]
3 month old issue but i might consider

**Comment by notcarlton** [comment]
i've messed with packaging projects for a while now and i cannot get this to work like at all

issue is up for grabs if someone else would like to implement

**Comment by CXCubeHD** [comment]
> i've messed with packaging projects for a while now and i cannot get this to work like at all

I should be able to do that easily, already have that done multiple times with ChronClient
