### ISSUE TITLE
Launcher starts and closes almost instantly

### ISSUE THREAD

**Issue by miqumi** [JiayiSoftware/JiayiLauncher#28]
.NET was installed by the Jiayi installer ; 
I click the start menu shortcut and the Launcher window appears and disappears almost instantly.
`taskkill` reveals no process like `JiayiLauncher.exe` is up

**Comment by notcarlton** [comment]
check log directory for a crash log `%localappdata%\JiayiLauncher\Logs`

**Comment by miqumi** [comment]
[21:19:37] [JiayiSettings - Info]: Loaded settings.
[21:19:37] [JiayiSettings - Info]: Saved settings.
[21:19:37] [ThemeManager - Info]: Applied theme.
[21:19:37] [JiayiStats - Info]: Created new stats file.

And this is the [settings.json](https://github.com/JiayiSoftware/JiayiLauncher/files/13687057/settings.json)

**Comment by miqumi** [comment]
mauuu
