### ISSUE TITLE
Timeout while downloading from jiyayi.mcpeplayground.com. Also Profram doesn't do anything.

### ISSUE THREAD

**Issue by hereBeDragons781** [JiayiSoftware/JiayiLauncher#32]
![image](https://github.com/JiayiSoftware/JiayiLauncher/assets/140696633/ef76d3aa-3eee-4e94-9193-2d3c688773eb)

Prety Obvius Fixes:
1. Use Github Actions ( free for public repos ).
2. Use a normal DDL site like Mediafire.

**Comment by notcarlton** [comment]
the server that hosts the installer is down atm. we're working on it
