### ISSUE TITLE
[Suggestion] Use IApplicationActivationManager to launch UWP apps.

### ISSUE THREAD

**Issue by Aetopia** [JiayiSoftware/JiayiLauncher#53]
Use [`IApplicationActivationManager`](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iapplicationactivationmanager) to launch UWP apps. 

The current launch + injection system uses a convoluted mechanism to launch the game:

- Get & check if Minecraft is actually installed.

- Launch the game using the acquired package data.

- Attempt to find a running instance of the game.

- Wait for a said amount of modules to be loaded.

Using `IApplicationActivationManager` removes any need to use mechanism since:

- All methods within this interface:
   
   - Waits for an UWP app to fully launch.

   - Returns the actual Process ID of the UWP app.

- You can launch an UWP app by passing CLI args, files & even URI protocols.

- Additionally this is the "proper" way of launching UWP apps from a desktop application.

**Comment by phasephasephase** [comment]
i'll look into it

**Comment by phasephasephase** [comment]
it might wait for the app to launch, but does it wait for the game to load? that's why it waits for modules

**Comment by Aetopia** [comment]
Yes it does, it waits for the app to fully launch the underlying process.

**Comment by phasephasephase** [comment]
when i say load i mean the game is 100% loaded and i see the title screen

**Comment by Aetopia** [comment]
No it doesn't do that. It waits for a UWP app to spawn the main process and then returns.

I am not really sure what's the point to wait for a X number of modules to be loaded.

**Comment by phasephasephase** [comment]
to prevent some mods from immediately crashing the game because they were injected too early

**Comment by Aetopia** [comment]
> to prevent some mods from immediately crashing the game because they were injected too early

https://github.com/JiayiSoftware/JiayiLauncher/blob/master/JiayiLauncher/Features/Game/Minecraft.cs

I have injected clients like Flarial & my own DLLs and they work with zero issues using this API.

Some parts of the current system can be retained but we ditch the current launch system and use this API instead, you can also get the underlying AppListEntry for MCBE to obtain the Application User Model ID.

**Comment by phasephasephase** [comment]
i said some mods because some mods don't wait for the game to load themselves

**Comment by phasephasephase** [comment]
that's where the crash comes from, they try to access parts of the game that haven't loaded yet

**Comment by Aetopia** [comment]
> i said some mods because some mods don't wait for the game to load themselves

In that case, just replace the current launch system with this API and retain the module number checks.

> Maybe leave the module number checks disabled by default and prompt the user to enable them if the game does potentially crash as a suggestion.

**Comment by phasephasephase** [comment]
i don't care about PID until it's time to inject, and even then i might not use it if the user loads an external mod
the game is more likely crash when we don't check for loaded modules, especially with older mods
